apiVersion: v1
kind: ConfigMap
metadata:
  name: converter-configmap
data:
  MP3_QUEUE: "mp3"
  VIDEO_QUEUE: "video"
  MONGO_URI: "mongodb://mongo:27017/videos"
  MONGO_MP3_URI: "mongodb://mongo:27017/mp3s"