apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: converter
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
      - name: converter
        image: deveshk237572/converter:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: converter-configmap
          - secretRef:
              name : converter-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

